---
title: "README"
author: "Anne Carroll"
date: "2024-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data and selected code used to assess USDA financial assistance program funding in Seeding Change to Manage Climate: Growing Insights from Four USDA Programs to Support Climate-Smart Agriculture by Elinor Benami, Anne Carroll, Kent D. Messer, Wei Zhang, and Michael Cecil. (link TBD)

### Data Download

The full data download can be found [here](https://doi.org/10.7910/DVN/MMXD4Y).

Contract Download Table - HUP.csv, Contract_Demographic_Download.csv, Contract_Political_Download.csv, Partnership_for_Climate_Smart_Commodities_Projects.xlsx, Practice_Political_Download.csv, and Producer Numbers by State.tab downloaded directly from sources below.

PCSC_data_with_HUP_info retains the information from Partnership_for_Climate_Smart_Commodities_Projects.xlsx with a binary column representing whether the project explicitly states that 50% or more of producers will be HUP or small, AND/OR that 50% or more of its funds will support HUP or small producers. Column added by Anne Carroll.

Program Funding and Outlays.tab is a manual creation derived from CBO data and projections, compiled by Anne Carroll.

Program Funding Levels is a manual creation derived from USDA Program Funding data, compiled by Kent D. Messer.

State and county geometries downloaded from Eric Celeste's website, but originally converted from the United States Census Cartographic Boundary Files. 

### Data Sources

[Partnerships for Climate Smart Commodities data](https://publicdashboards.dl.usda.gov/t/FPAC_PUB/views/PartnershipsForClimate-SmartCommodities/DataDownload?%3Aembed=y&%3AisGuestRedirectFromVizportal=y)

[Natural Resources Conservation Service data](https://www.farmers.gov/data/financial-assistance-download)

Contract Download Table downloaded from first dataset on Download tab of the website linked above, with Contract Status and Historically Underserved toggled to "All".

[Congressional Budget Office data](https://www.cbo.gov/system/files/2024-02/51317-2024-02-usda.pdf)

[Non-CRP USDA Program Funding data](https://publicdashboards.dl.usda.gov/t/FPAC_PUB/views/RCAConservationProgramObligations1/ConservationProgramObligations?%3Adisplay_count=n&%3Aembed=y&%3AisGuestRedirectFromVizportal=y&%3Aorigin=viz_share_link&%3AshowAppBanner=false&%3AshowVizHome=n)

[CRP USDA Program Funding Data](https://www.fsa.usda.gov/Assets/USDA-FSA-Public/usdafiles/Conservation/Excel/CRPHistoryState86-22.xlsx)

[NASS Census data](https://quickstats.nass.usda.gov/results/22649D58-38F7-3929-8C15-FE100B451C33)

[State and County Geometries](https://eric.clst.org/tech/usgeojson/)

### State Groupings by Region

States are occasionally grouped by region in the code, justified by either [NASS regions](https://www.nass.usda.gov/Statistics_by_State/RFO/index.php) or [USDA IRA Data Visualization Tool regions] (https://publicdashboards.dl.usda.gov/t/FPAC_PUB/views/InflationReductionActDataVisualizationTool/IRAEndofYearReport?%3Aembed=y&%3AisGuestRedirectFromVizportal=y).

### Coding Credit

"source2" function borrowed from Matthew Plourde on Stack Overflow [here](https://stackoverflow.com/questions/12214963/source-only-part-of-a-file).

### Scripts

* scripts/1-load_data - Script for loading data from dataverse.

* scripts/2-clean_data - Script for cleaning loaded data and preparing it for analysis.

* scripts/3-figures - Scripts for generating figures.

* scripts/4-tables - Scripts for generating select tables.

* scripts/5-stats - Scripts for generating select statistics.
